[package]
name = "concord-irc"
version = "0.1.0"
authors = ["Ratys <ratysz@gmail.com>"]

[dependencies]
config = "0.8"
futures = "0.1"
irc = "0.13"
log = "0.4"
serenity = "0.5"
simplelog = "0.5"
systray = "0.2"
text_io = "0.1"